-- vim.cmd([[hi TSKeyword gui=bold cterm=bold]])
-- vim.cmd([[hi Function gui=bold cterm=bold]])
-- vim.cmd([[hi TSKeywordFunction gui=italic,bold cterm=italic,bold]])
-- vim.cmd([[hi TSVariableBuiltin gui=italic cterm=italic]])
vim.api.nvim_set_hl(0, "Folded", { link = "Normal" })
